[package]
name = "using_deref_trait"
version = "0.1.0"
authors = ["Seonghyeon Kim <self@seonghyeon.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
